services:
  - type: web
    name: job-backend
    env: node
    rootDir: backend
  buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start:prod
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
